### PR TITLE
Completed function refactoring for all modules.

### PR DESCRIPTION
**Pull request by paras009**
I have built functions for all modules which has reduced all of the boilerplate code.
@hugobowne Please review the changes.

### CODE REVIEW

**Comment by hugobowne** [comment]
thanks, @paras009, this is great. Pedagogically, my plan is to *not* write the functions until we get to "recovered" -- i'll get everybody to write all the code the first time, then we'll copy&paste the second, then we'll write the functions

Are you able to edit this PR to reflect this?

Essentially, keep "Confirmed" & "Deaths" as they were previously, *then* include functions, *then* use them on "recovered".

LMK if you need clarification here.

**Comment by dsp09** [comment]
Sure, I'll do that and update in next PR.

**Comment by paras009** [comment]
@hugobowne please verify the changes and let me know if they are good or still require some modifications.
Thanks!

**Comment by hugobowne** [comment]
this looks great! I'll make some other edits over the weekend, & let you know what else I'm thinking.

**Pull request merged**
